linters:
  csslint: 
    fixer: true
    ignore: 'box-model,ids'
  checkstyle:
    config: ./checkstyle.xml
  eslint:
    config: './eslint.config'
    fixer: true
  
fixers: 
  enable: true
  
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
